server:
  port: 8080

spring:
  application:
    name: spring-prometheus-grafana

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'

  metrics:
    tags:
      application: ${spring.application.name}
