package com.ikang.webservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-05-31T17:32:55.740+08:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "authorName",
                  wsdlLocation = "classpath:wsdl/author.wsdl",
                  targetNamespace = "http://www.ikang.com/webservice")
public class AuthorName extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.ikang.com/webservice", "authorName");
    public final static QName AuthorPortName = new QName("http://www.ikang.com/webservice", "authorPortName");
    static {
        URL url = AuthorName.class.getClassLoader().getResource("wsdl/author.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(AuthorName.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/author.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AuthorName(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AuthorName(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthorName() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AuthorName(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AuthorName(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AuthorName(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AuthorPortType
     */
    @WebEndpoint(name = "authorPortName")
    public AuthorPortType getAuthorPortName() {
        return super.getPort(AuthorPortName, AuthorPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthorPortType
     */
    @WebEndpoint(name = "authorPortName")
    public AuthorPortType getAuthorPortName(WebServiceFeature... features) {
        return super.getPort(AuthorPortName, AuthorPortType.class, features);
    }

}
