package com.ikang.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-05-31T17:32:55.713+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://www.ikang.com/webservice", name = "authorPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface AuthorPortType {

    @WebMethod
    @RequestWrapper(localName = "getAuthorByName", targetNamespace = "http://www.ikang.com/webservice", className = "com.ikang.webservice.GetAuthorByName")
    @ResponseWrapper(localName = "getAuthorByNameResponse", targetNamespace = "http://www.ikang.com/webservice", className = "com.ikang.webservice.GetAuthorByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AuthorDto getAuthorByName(@WebParam(name = "authorName", targetNamespace = "") String authorName);

    @WebMethod
    @RequestWrapper(localName = "getAuthorString", targetNamespace = "http://www.ikang.com/webservice", className = "com.ikang.webservice.GetAuthorString")
    @ResponseWrapper(localName = "getAuthorStringResponse", targetNamespace = "http://www.ikang.com/webservice", className = "com.ikang.webservice.GetAuthorStringResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getAuthorString(@WebParam(name = "authorName", targetNamespace = "") String authorName);

    @WebMethod
    @RequestWrapper(localName = "getAuthorList", targetNamespace = "http://www.ikang.com/webservice", className = "com.ikang.webservice.GetAuthorList")
    @ResponseWrapper(localName = "getAuthorListResponse", targetNamespace = "http://www.ikang.com/webservice", className = "com.ikang.webservice.GetAuthorListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<AuthorDto> getAuthorList();
}
