scrape_configs:
# 任意写，建议英文，不包含特殊字符
- job_name: 'spring'
  # 多久采集一次数据
  scrape_interval: 15s
  # 采集时的超时时间
  scrape_timeout: 10s
  # 采集的路径是啥
  metrics_path: '/actuator/prometheus'
  # 采集的服务器地址，设置成上面 Spring Boot 应用所在的服务器具体地址
  static_configs:
  - targets: ['172.16.98.219:8080']
